### PR TITLE
[mini] Allow shifting managed pointers.

### PR DESCRIPTION
**Pull request by zfigura**
Needed by PUBG Lite launcher.

### CODE REVIEW

**Comment by madewokherd** [comment]
Okay, I gotta see how they're using this.

**Comment by madewokherd** [comment]
I'm wondering how Mono's GC will deal with the possibility of invalid managed pointers here, or temporarily disappearing references.

**Comment by zfigura** [comment]
Yeah, on reflection I don't think this is right either. I'll do some more investigation.

**Comment by zfigura** [comment]
Okay, so the problem is it's essentially implementing wcslen() by subtracting an unmanaged pointer from a managed one, then shifting the result right by 1.

More specifically, we have this:

```cil
.namespace '<CppImplementationDetails>'
{
  .class private sequential ansi sealed beforefieldinit $ArrayType$$$BY0BAE@_W
  	extends [mscorlib]System.ValueType
  {
    .custom instance void class [mscorlib]System.Runtime.CompilerServices.UnsafeValueTypeAttribute::'.ctor'() =  (01 00 00 00 ) // ....

    .custom instance void class [mscorlib]System.Runtime.CompilerServices.NativeCppClassAttribute::'.ctor'() =  (01 00 00 00 ) // ....

    .pack 0
    .size 520

  } // end of class <CppImplementationDetails>.$ArrayType$$$BY0BAE@_W
}
```
which is a WCHAR[MAX_PATH], and then
```
	.locals (
...
		valuetype <CppImplementationDetails>.$ArrayType$$$BY0BAE@_W*	V_4,
...
		valuetype <CppImplementationDetails>.$ArrayType$$$BY0BAE@_W	V_20)
...
	                        IL_0242:  ldloca.s 20
	                        IL_0244:  stloc.s 4
	                        IL_0246:  ldloca.s 20
	                        IL_0248:  ldind.i2 
	                        IL_0249:  brfalse.s IL_025a

	                        IL_024b:  ldloc.s 4
	                        IL_024d:  ldc.i4.2 
	                        IL_024e:  conv.i8 
	                        IL_024f:  add 
	                        IL_0250:  stloc.s 4
	                        IL_0252:  ldloc.s 4
	                        IL_0254:  unaligned. 0x01
	                        IL_0257:  ldind.i2 
	                        IL_0258:  brtrue.s IL_024b

	                        IL_025a:  ldloc.s 4
	                        IL_025c:  ldloca.s 20
	                        IL_025e:  sub 
	                        IL_025f:  ldc.i4.1 
	                        IL_0260:  shr 
```

Intuitively what comes out of "sub" shouldn't be a managed pointer, it should be an integer type. But I'm not sure if that's actually the right thing to do, and I'm not sure how to get there either if it is. I don't exactly know how to test any of this.

**Comment by zfigura** [comment]
Actually, from ECMA-335 § III.1.1.5:

"There are two kinds of pointers: unmanaged pointers and managed pointers. For pointers into the
same array or object (see Partition I), the following arithmetic operations are defined:
...
* Two pointers, regardless of kind, can be subtracted one from the other, producing a
signed integer that specifies the number of bytes between the addresses they
reference.

None of these operations is allowed in verifiable code."

So I think the better solution is to amend bin_num_table so that STACK_PTR - STACK_MP produces... something that's not STACK_MP, though I don't know what. STACK_I4?

Adding to the problem is the apparent fact that Mono throws both native int types and pointer types into STACK_PTR. Probably the former should still be treated as an integer for the purposes of pointer arithmetic, but the latter shouldn't. So I guess we may need to introduce another type STACK_UP.

**Comment by madewokherd** [comment]
Wouldn't it be INTPTR_TYPE?

**Comment by zfigura** [comment]
Sounds likely.

**Comment by madewokherd** [comment]
Sorry, I lost track of this, is it still an issue?

**Comment by zfigura** [comment]
PUBG Lite seems to have died [1], so I'll have to see if anyone who filed the bug still has a copy of the launcher.

Or we just abandon this report because the program is dead. I never got around to fixing it the right(er) way and I don't think it's really worth spending effort on.

[1] https://lite.pubg.com/2021/03/30/notice-april-29-service-termination-notice/

**Pull request closed without merging**
