### PR TITLE
[metadata] Support _VtblGap special method for COM imported interfaces.

### PR DESCRIPTION
**Pull request by gofman**
I encountered that in Warhammer Vermintide 2 launcher which is using MS Edge WebView2 embedding. The special method is encountered in WebView2 internal C# classes.  

The test suggests that the special method is recognized purely by name, no attribute is needed for it to take the specified number of slots.

My understanding that this special method is used in COM imported interfaces when the interface extends some other interface (like ITest2 in the example). Each derived interface still has InterfaceType(ComInterfaceType.InterfaceIsIUnknown) and from vtable layout point of view should still have all the methods from the base interface defined. VtblGap is inserted to avoid defining each method from the base interface. I only saw this used for the native COM interfaces used by managed code from classes created in native COM. I guess the interfaces implemented in Mono shouldn't have VtblGap.   

So the patch only adjusts the vtable slot indexes for the interface and doesn't attempt to make it work somehow for the vtables which should be generated by Mono. The latter would be much more complicated but I hope it is not needed.

[test.zip](https://github.com/madewokherd/mono/files/9161580/test.zip)

### CODE REVIEW

**Comment by madewokherd** [comment]
Interesting that rtspecialname isn't required. I guess they fixed that in .NET Core.

**Comment by madewokherd** [comment]
I'll look a little later at how these method fields are used, but I think this is probably good as long as the new test works and CI passes. CI hasn't run in a while so there may be unrelated failures, you can let me look first if you're not sure once it finishes. I can still merge the patch as long as any failures we get are not related.

**Comment by gofman** [comment]
The failure on linux-test seems to be this:

"The following packages have unmet dependencies:
 winehq-devel : Depends: wine-devel (= 7.13~focal-1)"

So unlikley PR related.

**Comment by madewokherd** [comment]
OK, unless I can get that fixed it's going to block me until we complete the office move at CodeWeavers, I need access to my work desktop.

**Pull request merged**
